name: tag latest version
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  validate:
    runs-on: ubuntu-22.04
    permissions:
      actions: read
      checks: write
      contents: write
      id-token: write
      statuses: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: '22.x'

      - name: check node version
        run: node --version

      - uses: oven-sh/setup-bun@v2
        with:
            bun-version: latest
            # bun-download-url: "https://raw.githubusercontent.com/190n/bun-sigbus-repro/refs/heads/master/bun-linux-x64-profile.zip"

      - name: install coredumpctl
        run: sudo apt install -y systemd-coredump

      - name: cause a segfault
        run: |
          ulimit -c unlimited
          sudo /home/runner/.bun/bin/bun install --frozen-lockfile
          mkdir -p crashes
          sudo cp /var/lib/systemd/coredump/* crashes
          sudo chown runner: crashes/*
          chmod 644 crashes/*

      - uses: actions/upload-artifact@master
        with:
          name: crashes
          path: crashes

      # - name: Validate
      #   run: bun nx run-many -t lint test -p components css
