name: tag latest version
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  validate:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      checks: write
      contents: write
      id-token: write
      statuses: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: oven-sh/setup-bun@v2
        with:
            bun-version-file: ".bun-version"

      - name: cause a segfault
        run: |
          ulimit -c unlimited
          clang -w -O0 -g3 -o crash crash.c
          sudo ./crash || true
        # sudo bun install --frozen-lockfile

      - name: look around
        run: find /var -name 'core.*' -or -name '*.crash' 2>/dev/null

      - uses: actions/upload-artifact@master
        with:
          name: crashes
          path: /var/lib/systemd/coredump

      # - name: Validate
      #   run: bun nx run-many -t lint test -p components css
