name: tag latest version
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  validate:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      checks: write
      contents: write
      id-token: write
      statuses: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: oven-sh/setup-bun@v2
        with:
            bun-download-url: "https://github.com/oven-sh/bun/releases/download/bun-v1.1.29/bun-linux-x64-profile.zip"

      - name: install coredumpctl
        run: sudo apt install -y systemd-coredump

      - name: cause a segfault
        run: |
          ulimit -c unlimited
          sudo bun-profile install --frozen-lockfile || true
          mkdir -p crashes
          sudo cp /var/lib/systemd/coredump/* crashes
          sudo chown runner: crashes/*
          chmod 644 crashes/*

      - uses: actions/upload-artifact@master
        with:
          name: crashes
          path: crashes

      # - name: Validate
      #   run: bun nx run-many -t lint test -p components css
